using System;
using System.Diagnostics;
using System.IO;
using System.Runtime.InteropServices;

// Include the PDF Generator.
using PhantomJs.NetCore;

namespace ConsoleApplication
{
    public class ExampleProgram
    {
        public static void Main(string[] args)
        {
            string currentDirectory = Directory.GetCurrentDirectory();
            string phantomJsRootFolder = Path.Combine(currentDirectory, "PhantomJsRoot");

            // the pdf generator needs to know the path to the folder with .exe files.
            PdfGenerator generator = new PdfGenerator(phantomJsRootFolder);

            string htmlToConvert = 
@"
<!DOCTYPE html>
<html>
<head>

</head>
<body>
    <h1>Hello World!</h1>
    <p>This PDF has been generated by PhantomJs ;)</p>
</body>
</html>
";
            // Generate pdf from html and place in the current folder.
            string pathOftheGeneratedPdf = generator.GeneratePdf(htmlToConvert,currentDirectory);

            Console.WriteLine("Pdf generated at: "+pathOftheGeneratedPdf);
        }
    }
}
